import { Feirante, Product, Category } from './types'

export const feirantes: Feirante[] = [
  {
    id: "1",
    name: "João da Horta",
    rating: 4.8,
    time: "5h às 16h",
    avatar: "/placeholder.svg?height=80&width=80&text=JH",
    description:
      "Especialista em verduras orgânicas há mais de 20 anos. Cultivo próprio sem agrotóxicos, direto da fazenda para sua mesa.",
    specialties: ["Verduras Orgânicas", "Temperos Frescos", "Folhas"],
    location: "Zona Sul - SP",
    isOpen: true,
  },
  {
    id: "2",
    name: "Maria das Frutas",
    rating: 4.9,
    time: "6h às 15h",
    avatar: "/placeholder.svg?height=80&width=80&text=MF",
    description:
      "Frutas selecionadas e sempre frescas. Trabalho com produtores locais para garantir a melhor qualidade.",
    specialties: ["Frutas Tropicais", "Frutas da Estação", "Sucos Naturais"],
    location: "Centro - SP",
    isOpen: true,
  },
  {
    id: "3",
    name: "Seu Antônio",
    rating: 4.7,
    time: "7h às 17h",
    avatar: "/placeholder.svg?height=80&width=80&text=SA",
    description: "Tradição familiar de 3 gerações. Legumes e tubérculos frescos, direto do produtor.",
    specialties: ["Legumes", "Tubérculos", "Raízes"],
    location: "Zona Norte - SP",
    isOpen: false,
  },
  {
    id: "4",
    name: "Dona Rosa",
    rating: 4.6,
    time: "5h às 14h",
    avatar: "/placeholder.svg?height=80&width=80&text=DR",
    description: "Especializada em produtos orgânicos certificados. Qualidade premium para sua família.",
    specialties: ["Orgânicos", "Grãos", "Cereais"],
    location: "Zona Oeste - SP",
    isOpen: true,
  },
]

export const products: Product[] = [
  {
    id: "1",
    name: "Alface Americana",
    price: 3.5,
    unit: "unidade",
    image: "🥬",
    category: "folhas",
    description: "Alface fresca e crocante, ideal para saladas",
  },
  {
    id: "2",
    name: "Couve Manteiga",
    price: 2.8,
    unit: "maço",
    image: "🥬",
    category: "folhas",
    description: "Couve orgânica, rica em nutrientes",
  },
  {
    id: "3",
    name: "Rúcula",
    price: 4.2,
    unit: "maço",
    image: "🥬",
    category: "folhas",
    description: "Rúcula selvagem com sabor marcante",
  },
  {
    id: "4",
    name: "Banana Prata",
    price: 4.5,
    unit: "kg",
    image: "🍌",
    category: "frutas",
    description: "Banana doce e nutritiva, rica em potássio",
  },
  {
    id: "5",
    name: "Maçã Gala",
    price: 8.9,
    unit: "kg",
    image: "🍎",
    category: "frutas",
    description: "Maçã crocante e doce, perfeita para lanches",
  },
  {
    id: "6",
    name: "Laranja Lima",
    price: 3.2,
    unit: "kg",
    image: "🍊",
    category: "frutas",
    description: "Laranja doce e suculenta, ideal para sucos",
  },
  {
    id: "7",
    name: "Tomate Salada",
    price: 6.9,
    unit: "kg",
    image: "🍅",
    category: "legumes",
    description: "Tomate maduro e saboroso",
  },
  {
    id: "8",
    name: "Cenoura",
    price: 4.2,
    unit: "kg",
    image: "🥕",
    category: "legumes",
    description: "Cenoura doce e crocante",
  },
  {
    id: "9",
    name: "Batata Inglesa",
    price: 3.8,
    unit: "kg",
    image: "🥔",
    category: "tuberculos",
    description: "Batata de qualidade premium",
  },
]

export const categories: Category[] = [
  { id: "frutas", name: "Frutas", icon: "🍎" },
  { id: "folhas", name: "Folhas", icon: "🥬" },
  { id: "tuberculos", name: "Tubérculos", icon: "🥔" },
  { id: "legumes", name: "Legumes", icon: "🥕" },
  { id: "ovos", name: "Ovos", icon: "🥚" },
  { id: "graos", name: "Grãos", icon: "🌾" },
]
